# Generated by Django 5.0 on 2024-03-03 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='url')),
                ('body', models.CharField(blank=True, max_length=10000, verbose_name='body')),
                ('body_html', models.TextField(blank=True, null=True, verbose_name='html')),
                ('image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='image alt')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date submitted')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'get_latest_by': 'submit_date',
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
